import ReactorModel.Objects.Reactor.Theorems.Accessible
import ReactorModel.Objects.Reactor.Theorems.Basic
import ReactorModel.Objects.Reactor.Theorems.Extensional
import ReactorModel.Objects.Reactor.Theorems.Indexable
import ReactorModel.Objects.Reactor.Theorems.Proper
import ReactorModel.Objects.Reactor.Theorems.Readable
import ReactorModel.Objects.Reactor.Theorems.WellFounded
import ReactorModel.Objects.Reactor.Theorems.WellIndexable
import ReactorModel.Objects.Reactor.Theorems.WellUpdatable