[package]
name = "reactor-model"
version = "0.1"
lean_version = "leanprover/lean4:nightly-2021-08-16"

[dependencies]
mathlib4 = { git = "https://github.com/leanprover-community/mathlib4", rev = "1f90636b38acaf8c6f3f5be9c71cbb6bec6ba5a8" }


