[package]
name = "reactor-model"
version = "0.1"
lean_version = "leanprover/lean4:nightly-2021-07-27"

[dependencies]
mathlib4 = { git = "https://github.com/leanprover-community/mathlib4", rev = "7822926636f86c197bf3b9d14b4ad3b4a34701a1" }


