[package]
name = "reactor-model"
version = "0.1"
lean_version = "leanprover/lean4:nightly-2021-07-11"

[dependencies]
mathlib4 = { git = "https://github.com/leanprover-community/mathlib4", rev = "1fd1cdc64b9a968e302ebd34af228b40cc05eb04" }


